### ISSUE TITLE
Duvida sobre commits

### ISSUE THREAD

**Issue by marinacollier** [marinacollier/jogo-da-velha-#1]
Professor, já que o **hydra** já está de volta, fiquei na duvida se era **melhor** :
- eu programar por lá e ir dando commits, 
- ou se coloco o código direto por aqui.... 

**_O que o senhor aconselha? :)_**

**Comment by drbeco** [comment]
Aproveite o Hydra... Faça lá o ex0 e as configurações iniciais. Já deixa tudo organizado

**Comment by marinacollier** [comment]
Coloco ele dentro de `discreta/rascunhos`
ou deixo fora?

**Comment by drbeco** [comment]
Pode criar uma pasta fora se preferir com vários programas do seu interesse. Por exemplo `/home/mcdam/fontes` ou outra que preferir

**Comment by marinacollier** [comment]
Ok professor, obrigada!!
- Já criei com o nome `testes`
